---
title: "test"
output: html_document
date: "2024-04-02"
---

```{r, warning=FALSE, message=FALSE}
#| echo: false
#| message: false
#| warning: false
#| results: hide

library(fredr)
library(readrba)
library(readabs)
library(xts)
library(tseries)
library(fUnitRoots) 
fredr_set_key("75b470c4883ecfd5a7b4185f30437bd0")
```

```{r, warning=FALSE, message=FALSE}
#| echo: false
#| message: false
#| warning: false

#Y variable
# AUD/USD exchange rate quarterly
#
ex_rate <- read_rba(series_id = "FXRUSD")
ex_rate$date <- as.Date(ex_rate$date)
erate <- xts(ex_rate$value, ex_rate$date)
erate <- apply.quarterly(erate,mean)
index(erate) <- seq(as.Date("1969-09-01"), by = "3 months", length.out = nrow(erate))


exr_link        = "https://query1.finance.yahoo.com/v7/finance/download/AUDUSD%3DX?period1=1149120000&period2=1703980800&interval=1mo&filter=history&frequency=1mo&includeAdjustedClose=true"
ex_rate <-read.csv(exr_link)
ex_rate$Date <- as.Date(ex_rate$Date)
erate <- xts(ex_rate$Adj.Close, ex_rate$Date)
erate <- apply.quarterly(erate,mean)


#gold price
gpricelink <- "https://query1.finance.yahoo.com/v7/finance/download/GC%3DF?period1=1262304000&period2=1703980800&interval=1mo&filter=history&frequency=1mo&includeAdjustedClose=true"
gprice  <- read.csv(gpricelink)
gprice$Date <- as.Date(gprice$Date)
gprice <- xts(gprice$Adj.Close, gprice$Date)
gprice <- apply.quarterly(gprice,mean)

# Australia real gdp seasonal adjusted quarterly
#rgdp_au <- read_rba(series_id = "GGDPCVGDP")
rgdp_au <- read_abs(series_id = "A2304404C")  
rgdp_au <- xts::xts(rgdp_au$value, rgdp_au$date)

#cash rate/interest rate of AUS quartly
cashrate<- read_cashrate(type = c("target"))
crate_au<- xts(cashrate$value, cashrate$date)
crate_au<- apply.quarterly(crate_au,mean)
crate_au<- xts(crate_au, seq(as.Date("1990-03-01"), by = "quarter", length.out = length(crate_au)))

#CPI quartly
# cpi_au <- read_rba(series_id = "GCPIAG")
cpi_au <- read_abs(series_id = "A2325846C")  
cpi_au <- xts::xts(cpi_au$value, cpi_au$date)

#unemployment rate quartly
#unemprate <-read_rba(series_id = "GLFSURSA")
unemprate <- read_abs(series_id = "A84423050A") 
unemr_au<- xts(unemprate$value, unemprate$date)
unemr_au<- apply.quarterly(unemr_au,mean)

# International Trade in Goods and Services seasonal adjusted_quartly
exportaus <- read_abs(series_id = "A2718603V")   
expor_au<- xts(exportaus $value, exportaus $date)
expor_au<- abs(expor_au)
expor_au<- apply.quarterly(expor_au,mean)

importaus <- read_abs(series_id = "A2718577A")     
impor_au<- xts(importaus$value, importaus$date)
impor_au<- apply.quarterly(impor_au,mean)


# America data
# us gdp
rgdpus     <- fredr(series_id = "GDPC1")
rgdp_us     <- to.quarterly(xts(rgdpus$value, rgdpus$date), OHLC = FALSE)
index(rgdp_us) <- seq(as.Date("1947-03-01"), by = "3 months", length.out = nrow(rgdp_us))

#Federal Funds Effective Rate/interest rate quartly
usdratelink = "https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23e1e9f0&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1318&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=DFF&scale=left&cosd=1954-07-01&coed=2024-03-01&line_color=%234572a7&link_values=false&line_style=solid&mark_type=none&mw=3&lw=2&ost=-99999&oet=99999&mma=0&fml=a&fq=Daily%2C%207-Day&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2024-04-01&revision_date=2024-04-01&nd=1954-07-01"
crate_us <- read.csv(usdratelink)
crate_us$DATE <- as.Date(crate_us$DATE)
crate_us <- xts(crate_us$DFF, order.by = crate_us$DATE)
crate_us <- apply.quarterly(crate_us,mean)
crate_us<- xts(crate_us, seq(as.Date("1954-09-01"), by = "quarter", length.out = length(crate_us)))

# cpi quartly
cpiusd  <- fredr(series_id = "USACPIALLMINMEI")
cpi_us<- xts(cpiusd$value, cpiusd$date)
cpi_us<- apply.quarterly(cpi_us,mean)

# unemployment quartly
unemprate_usd = fredr(series_id = "UNRATE")
unemr_us <- xts(unemprate_usd$value, unemprate_usd$date)
unemr_us<- apply.quarterly(unemr_us,mean)

#export_usd——quartly
usdexportink = "https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23e1e9f0&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1318&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=EXPGS&scale=left&cosd=1947-01-01&coed=2023-10-01&line_color=%234572a7&link_values=false&line_style=solid&mark_type=none&mw=3&lw=2&ost=-99999&oet=99999&mma=0&fml=a&fq=Quarterly&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2024-03-30&revision_date=2024-03-30&nd=1947-01-01"
expor_us <- read.csv(usdexportink)
expor_us$DATE <- as.Date(expor_us$DATE)
expor_us <- xts::xts(expor_us$EXPGS, order.by = expor_us$DATE)
index(expor_us) <- seq(as.Date("1947-03-01"), by = "3 months", length.out = nrow(expor_us))

#import_usd_quartly
usdimportlink = "https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23e1e9f0&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1318&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=IMPGS&scale=left&cosd=1947-01-01&coed=2023-10-01&line_color=%234572a7&link_values=false&line_style=solid&mark_type=none&mw=3&lw=2&ost=-99999&oet=99999&mma=0&fml=a&fq=Quarterly&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2024-03-30&revision_date=2024-03-30&nd=1947-01-01"
impor_us <- read.csv(usdimportlink)
impor_us$DATE <- as.Date(impor_us$DATE)
impor_us <- xts::xts(impor_us$IMPGS, order.by = impor_us$DATE)
index(impor_us) <- seq(as.Date("1947-03-01"), by = "3 months", length.out = nrow(impor_us))

```

```{r}
# log transformation of data
cpi_au <- log(cpi_au)
cpi_us <- log(cpi_us)
rgdp_au <- log(rgdp_au)
rgdp_us <- log(rgdp_us)
impor_au <- log(impor_au)
impor_us<- log(impor_us)
expor_au <- log(expor_au)
expor_us<- log(expor_us)
gprice <- log(gprice)
```


```{r}
#| echo: false
#| message: false
#| warning: false
#| results: hide
#| 
# All Variables
merged_data = na.omit(merge(erate,
                            cpi_au, cpi_us, 
                            crate_au, crate_us, 
                            expor_au, expor_us,  
                            impor_au, impor_us, 
                            rgdp_au, rgdp_us,
                            unemr_au, unemr_us))
colnames(merged_data)   = c("exchange rate",  
                         "cpi_au",    "cpi_us", 
                         "cashrate_au",  "cashrate_us", 
                         "export_au", "export_us",
                         "import_au",   "import_us",
                         "realgdp_au", "realgdp_us",
                         "unemployemtrate_au", "unemployemtrate_us")


```


```{r all variables plot}
#| echo: false
#| message: false
#| warning: false

par(mfcol = c(4, 2), mar=c(2,2,2,2))
for (i in 1:6) { 
  ts.plot(merged_data[, i], main = colnames(merged_data)[i], 
          ylab = "", xlab = "")
}

par(mfrow = c(4, 2), mar=c(2,2,2,2))
for (i in 7:13) { 
  ts.plot(merged_data[, i], main = colnames(merged_data)[i], 
          ylab = "", xlab = "")
}

```

```{r}
x_varibales <-  na.omit(merge(gprice,
                            cpi_au, cpi_us, 
                            crate_au, crate_us, 
                            expor_au, expor_us,  
                            impor_au, impor_us, 
                            rgdp_au, rgdp_us,
                            unemr_au, unemr_us))
colnames(x_varibales)   = c("gold price", 
                         "cpi_au",    "cpi_us", 
                         "cashrate_au",  "cashrate_us", 
                         "export_au", "export_us",
                         "import_au",   "import_us",
                         "realgdp_au", "realgdp_us",
                         "unemployemtrate_au", "unemployemtrate_us")
```

```{r}
#| echo: true
#| message: false
#| warning: false
# Compute correlation matrix
correlation_matrix <- cor(merged_data)

# Find the row number corresponding to "erate"
erate_row <- which(rownames(correlation_matrix) == "erate")

# Extract correlations between erate and other variables
correlations_erate <- correlation_matrix[erate_row, names(merged_data) != "erate"]

# Print correlation values
print(correlations_erate)

```

# Augmented Dickey-Fuller test for log transformed variables except exchange rate  and cash rate.
```{r}
par(mfcol = c(3, 2), mar=c(2,2,2,2))
for (i in 1:6){
acf = acf(merged_data[,i], plot = FALSE)[1:20]
plot(acf, main = "")
title(main = paste(colnames(merged_data)[i]), line = 0.5)
}

par(mfrow = c(3, 2), mar=c(2,2,2,2))
for (i in 7:13){
acf = acf(merged_data[,i], plot = FALSE)[1:20]
plot(acf, main = "")
title(main = paste(colnames(merged_data)[i]), line = 0.5)
}
```

```{r}
adf_test <- list()
for (i in 1:13) {
  adf_result = adf.test(merged_data[,i], k = 4)
  adf_test[[i]] <- adf_result
}

print(adf_test)
```


```{r}
adf_table <- data.frame(p_value = numeric(length(adf_test)))

for (i in 1:length(adf_test)) {adf_table[i, "p_value"] = round(adf_test[[i]]$p.value,3)
}

rownames(adf_table)<- c("exchange rate", 
                         "cpi_au",    "cpi_us", 
                         "cashrate_au",  "cashrate_us", 
                         "export_au", "export_us",
                         "import_au",   "import_us",
                         "realgdp_au", "realgdp_us",
                         "unemployemtrate_au", "unemployemtrate_us")

colnames(adf_table)<- c("P-value")
print(adf_table)

#clear that all >0.05 and reject the null that is stationary
```

```{r}
#take the first difference
dff_merged_data <- na.omit(merged_data - lag(merged_data))
```

```{r}
# ADF test
dff_adf_ <- list()
for (i in 1:13) {
  dff_adf_result = adf.test(dff_merged_data[,i], k = 4)
  dff_adf_[[i]] <- dff_adf_result
}

# View the ADF test results
dff_adf_table <- data.frame(p_value = numeric(length(dff_adf_)))

# Fill in the data frame with the test results
for (i in 1:length(dff_adf_)) {
  dff_adf_table[i, "p_value"] = round(dff_adf_[[i]]$p.value,3)

}
rownames(dff_adf_table)<- c("exchange rate",
                         "cpi_au",    "cpi_us", 
                         "cashrate_au",  "cashrate_us", 
                         "export_au", "export_us",
                         "import_au",   "import_us",
                         "realgdp_au", "realgdp_us",
                         "unemployemtrate_au", "unemployemtrate_us")

colnames(dff_adf_table)<- c("P-value")
print(dff_adf_table)
```

```{r}
#take the second difference 
dff_dff_data <- subset(dff_merged_data, select = -c(realgdp_us))

# Create a new dataset with the remaining variables

dff_dff_merged_data <- na.omit(dff_dff_data- lag(dff_dff_data)) 
```

```{r}
dff_dff_adf_ <- list()
for (i in 1:12) {
  dff_dff_adf_result = adf.test(dff_dff_merged_data[,i], k = 4)
  dff_dff_adf_[[i]] <- dff_dff_adf_result
}

# View the ADF test results
dff_dff_adf_table <- data.frame(p_value = numeric(length(dff_dff_adf_)))

# Fill in the data frame with the test results
for (i in 1:length(dff_dff_adf_)) {
  dff_dff_adf_table[i, "p_value"] = round(dff_dff_adf_[[i]]$p.value,3)

}
rownames(dff_dff_adf_table)<- c("exchange rate", 
                         "cpi_au",    "cpi_us", 
                         "cashrate_au",  "cashrate_us", 
                         "export_au", "export_us",
                         "import_au",   "import_us",
                         "realgdp_au",
                         "unemployemtrate_au", "unemployemtrate_us")

colnames(dff_dff_adf_table)<- c("P-value")
print(dff_dff_adf_table)
```





```{=tex}
\begin{align}
Y =\begin{pmatrix}
 y_{crateau_,1}&  y_{rgdpau_,1}&  y_{cpiau_,1}&  y_{unemrau_,1}&  y_{imporau_,1}&  y_{exporau_,1}&  y_{crateus_,1}&  y_{rgdpus_,1}&  y_{cpius_,1}&  y_{unemrus_,1}&  y_{imporus_,1}&  y_{exporus_,1}\\
 y_{crateau_,2}&  y_{rgdpau_,2}&  y_{cpiau_,2}&  y_{unemrau_,2}&  y_{imporau_,2}&  y_{exporau_,2}&  y_{crateus_,2}&  y_{rgdpus_,2}&  y_{cpius_,2}&  y_{unemrus_,2}&  y_{imporus_,2}&  y_{exporus_,2}\\ \ \vdots & \vdots & \vdots  & \vdots & \vdots & \vdots& \vdots& \vdots& \vdots& \vdots& \vdots & \vdots\\

y_{crateau_,T}&  y_{rgdpau_,T}&  y_{cpiau_,T}&  y_{unemrau_,T}&  y_{imporau_,T}&  y_{exporau_,T}&  y_{crateus_,T}&  y_{rgdpus_,T}&  y_{cpius_,T}&  y_{unemrus_,T}&  y_{imporus_,T}&  y_{exporus_,T}
\end{pmatrix}
\end{align}
```